export class ButtonType {
  static reset = "reset";
  static addNew = "addNew";
  static save = "save";
  static delete = "delete";
  static edit = "edit";
  static update = "update";
  static print = "print";
  static preview = "preview";
  static config = "config";
  static trashRestore = "trashRestore";
  static viewLog = "viewLog";
  static closeModal = "closeModal";
  static okModal = "okModal";
  static cancelModal = "cancelModal";
  static apply = "apply";
  static custom = "custom";
  static selectAll = "selectAll";
  static unSelectAll = "unSelectAll";
  static toggleSelection = "toggleSelection";
  static submit = "submit";
  static cancelSubmit = "cancelSubmit";
  static approve = "approve";
  static cancelApprove = "cancelApprove";
  static assign = "assign";
  static unAssign = "unAssign";
  static hold = "hold";
  static unHold = "unHold";
  static dashboard = "dashboard";
  static complete = "complete";
  static unComplete = "unComplete";
  static back = "back";
}

export class ButtonPressed {
  static ok = "ok";
  static close = "close";
  static cancel = "cancel";
}

export class ButtonId {
  static addNew = 'btnAddNew';
  static save = 'btnSave';
  static delete = 'btnDelete';
  static edit = 'btnEdit';
  static update = 'btnUpdate';
  static print = 'btnPrint';
  static preview = 'btnPreview';
  static config = 'btnConfig';
  static trashRestore = 'btnTrashRestore';
  static viewLog = 'btnViewLog';
  static apply = 'btnApply';
  static submit = 'btnSubmit';
  static cancelSubmit = 'btnCancelSubmit';
  static approve = 'btnApprove';
  static cancelApprove = 'btnCancelApprove';
  static assign = 'btnAssign';
  static unAssign = 'btnUnAssign';
  static hold = 'btnHold';
  static unHold = 'btnUnHold';
  static dashboard = 'btnDashboard';
  static complete = 'btnComplete';
  static unComplete = 'btnUnComplete';
}
